# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        default:
            language: fr
            toolbar:
                 - { name: "styles", items: ['Italic', 'Underline', 'Strike', 'Blockquote', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Styles', 'Format','FontSize', '-', 'TextColor', 'BGColor'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            extraPlugins: ["codesnippet"]
        main_config:
            language: fr
            toolbar:
                - { name: "styles", items: ['code', 'Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Smiley', 'Image', 'Youtube', 'Embed',  'Table', 'Styles', 'Format','Font','FontSize', '-', 'TextColor', 'BGColor', 'Source'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            extraPlugins: ["codesnippet"]
        plugins:
        codesnippet:
            path:     "bundles/fosckeditor/plugins/codesnippet/" # with trailing slash
            filename: "plugin.js"